# Generated by Django 5.1.2 on 2024-11-28 21:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default=None, max_length=100)),
                ('platform', models.CharField(default=None, max_length=10)),
                ('install_size', models.SmallIntegerField(default=None)),
                ('link', models.CharField(default=None, max_length=300)),
                ('banner_link', models.CharField(default=None, max_length=300)),
                ('min_party_size', models.SmallIntegerField(default=None)),
                ('max_party_size', models.SmallIntegerField(default=None)),
                ('tags', models.CharField(default=None, max_length=300)),
                ('last_updated', models.DateTimeField(default=None, verbose_name='Last Updated')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date added')),
            ],
        ),
    ]
