# Generated by Django 5.1.2 on 2024-11-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='install_size',
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='last_updated',
            field=models.DateTimeField(default=None, null=True, verbose_name='Last Updated'),
        ),
    ]
