# Generated by Django 5.1.2 on 2024-11-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_game_install_size_alter_game_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.JSONField(default=None),
        ),
    ]
