# Generated by Django 5.1.2 on 2024-12-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_game_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discord_id', models.CharField(default=None, max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('avatar_link', models.CharField(default=None, max_length=100)),
                ('last_login', models.DateTimeField(default=None, null=True)),
                ('display_name', models.CharField(default=None, max_length=100)),
                ('display_name_last_changed', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
