# Generated by Django 5.1.2 on 2024-12-02 18:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_discorduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='first_login',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='First Login'),
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.discorduser')),
            ],
        ),
    ]
