# Generated by Django 5.1.2 on 2024-12-21 07:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_game_update_banner_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('rating', models.SmallIntegerField(default=None)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date added')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.discorduser')),
            ],
        ),
    ]
