# Generated by Django 5.1.4 on 2024-12-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_rating_game_alter_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='average_rating',
            field=models.FloatField(default=None, null=True),
        ),
    ]
