# Generated by Django 5.1.4 on 2024-12-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_game_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='account_activated',
            field=models.BooleanField(default=False),
        ),
    ]
