# Generated by Django 5.1.4 on 2024-12-31 04:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_authtoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='expiry_date',
            field=models.DateTimeField(default=api.models.add_one_week, verbose_name='Expiry Date'),
        ),
    ]
