# Generated by Django 5.1.4 on 2025-01-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_authtoken_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='can_add_games',
            field=models.BooleanField(default=False),
        ),
    ]
