# Generated by Django 5.1.4 on 2025-01-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_discorduser_can_add_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='popularity_score',
            field=models.FloatField(default=None, null=True),
        ),
    ]
