# Generated by Django 5.1.4 on 2025-01-07 22:43

import api.models
import minio_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_game_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='banner_image',
            field=models.ImageField(default=None, null=True, storage=minio_storage.storage.MinioMediaStorage(), upload_to=api.models.format_banner_filename),
        ),
    ]
