services:
  backend:
    build:
      context: ./backend
    ports:
      - "15001:15001"
    env_file:
      - ./backend/.env.docker

  frontend:
    build:
      context: ./frontend/gamerater
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_DISCORD_CLIENT_ID: ${VITE_DISCORD_CLIENT_ID}
        VITE_FINAL_REDIRECT_URI: ${VITE_FINAL_REDIRECT_URI}
    ports:
      - "15000:80"
    env_file:
      - ./frontend/gamerater/.env.docker