services:
  backend:
    build:
      context: ./backend
    ports:
      - "15001:15001"
    env_file:
      - ./backend/.env.docker

  frontend:
    build:
      context: ./frontend/gamerater
    ports:
      - "15000:15000"
    volumes:
      - ./frontend-config.json:/usr/share/nginx/html/config.json