name: Build and Publish Docker Images

on:
  release:
    types:
      - published

jobs:
  build-and-push:
    name: Build and Publish Docker Images
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: |
          mrspacecarrot/gamerater-backend:latest
          mrspacecarrot/gamerater-backend:${{ github.event.release.tag_name }}

    - name: Build and push frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend/gamerater
        push: true
        tags: |
          mrspacecarrot/gamerater-frontend:latest
          mrspacecarrot/gamerater-frontend:${{ github.event.release.tag_name }}
        build-args: |
          VITE_API_URL=${{ secrets.FRONTEND_VITE_API_URL }}
          VITE_DISCORD_CLIENT_ID=${{ secrets.FRONTEND_VITE_DISCORD_CLIENT_ID }}
          VITE_FINAL_REDIRECT_URI=${{ secrets.FRONTEND_VITE_FINAL_REDIRECT_URI }}

  add-source-code:
    name: Add Source Code to Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create source_code.zip
      run: zip -r source_code.zip . -x .git/**

    - name: Upload source_code.zip to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./source_code.zip
        asset_name: source_code.zip
        asset_content_type: application/zip
